# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Guruprasath Gurusamy
title: Research Assistant
email: guru-prasath@outlook.com
#website: www.github.com/

# Dark theme
darkmode: true
#other options: false, never

# Social links
github_username:  gguruprasath
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: guruprasathg
twitter_username: 47ag108
instagram_username: guruprasath_
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Guru and I'm a research assistant in the Cognitive, Computational and Behavior Lab at Centre for Neuroscience, Indian Institute of Science, Bengaluru.

  I am most skilled in: <mark>Neuroimaging</mark> and <mark>talking to cats</mark>

  Research Interests: 
   - Cognitive and Computational Neuroscience
   - Neuroimaging and Neuromodulation
   - Computational Psychiatry
   - Machine Learning

# Projects Section
projects_title: Projects

# Experience Section
experience_title: Experience

# Education Section
educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Cognitve and Computational Neuroscience some of my other interests and hobbies are:
   - Amateur Astronomy
   - Utopian Sci-fi movies
   - Chasing my cat <mark>Leia</mark>[https://www.instagram.com/leia.kitty/]

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
